name: ci

on:
  workflow_dispatch: 
    
env:
  DOTNET_VERSION: "7.0.x"
  
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      
      - name: Setup .NET 7
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
        
      - name: test LS
        run: |
          echo "${{github.workspace}}"
          docker --version
          
      - name: Install dependencies
        run: dotnet restore
        working-directory: ./vasea
        
      - name: Build
        run: dotnet build --configuration Release --no-restore
        working-directory: ./vasea

#      - name: Upload artifact
#        uses: actions/upload-artifact@v4
#        with:
#          name: vasea
#          path: ./vasea/bin/Release/net7.0
#          if-no-files-found: error
#          retention-days: 1