name: ci

on:
  workflow_dispatch: 
    
#  push:
#    branches:
#      - master
    
jobs:
  build:
    runs-on: self-hosted
    working-directory: ./Vasea
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: ./Vasea
      
      - name: Setup .NET 7
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '7.0.x'
      
      - name: Install dependencies
        run: dotnet restore
        
      - name: Build
        run: dotnet build --configuration Release --no-restore
