name: ciDocker

on:
  workflow_dispatch: 
    
env:
  HOME: "/root"
  DOTNET_VERSION: "7.0.x"
  
jobs:
  build:
    runs-on: self-hosted
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Set up SSH
        uses: appleboy/ssh-action@master
        with:
          host: 10.10.11.101
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          endpoint: ssh://root@10.10.11.101
        
#      - name: Build and push
#        uses: docker/build-push-action@v5
#        with:
#          context: .
#          tags: Vasile:latest
#          outputs: type=docker,dest=/tmp/myimage.tar

      - name: Run Docker command
        run: |
          docker ps
          

      