name: ciDocker

on:
  workflow_dispatch: 
    
env:
  HOME: "/root"
  DOTNET_VERSION: "7.0.x"
  
jobs:
  build:
    runs-on: self-hosted
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Set up SSH
        uses: MrSquaare/ssh-setup-action@v3
        with:
          host: 10.10.11.101
          private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:   
          endpoint: ssh://root@10.10.11.101

      