name: ciDocker

on:
  workflow_dispatch: 
    
env:
  HOME: "/root"
  DOTNET_VERSION: "7.0.x"
  
jobs:
  build:
    runs-on: self-hosted
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Set up SSH
        uses: cross-the-world/ssh-scp-ssh-pipelines@latest
        with:
          host: 10.10.11.101
          user: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          pass: ${{ secrets.SSH_PASSPHRASE }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      